// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feed_exists.sql

package database

import (
	"context"
)

const feedExists = `-- name: FeedExists :one
SELECT EXISTS(
    SELECT 1 FROM feeds WHERE url = $1
)
`

// queries.sql
func (q *Queries) FeedExists(ctx context.Context, url string) (bool, error) {
	row := q.db.QueryRowContext(ctx, feedExists, url)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
