// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_user_by_name.sql

package database

import (
	"context"
)

const getUserName = `-- name: GetUserName :one
SELECT id, created_at, updated_at, name FROM users WHERE name = $1
`

func (q *Queries) GetUserName(ctx context.Context, name string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserName, name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}
