// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_exists.sql

package database

import (
	"context"
)

const userExists = `-- name: UserExists :one
SELECT EXISTS(
    SELECT 1 FROM users WHERE name = $1
)
`

// queries.sql
func (q *Queries) UserExists(ctx context.Context, name string) (bool, error) {
	row := q.db.QueryRowContext(ctx, userExists, name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
